### PR TITLE
PCM-1000 changes

### PR DESCRIPTION
**Pull request by renujhamtani**
@sshumake Please review.

### CODE REVIEW

**Comment by renujhamtani** [comment]
@sshumake Please review and merge. Not able to understand the inconsistency between the version in bower.json and actual tag version. Actual tag version would be 1.0.8 once i tag after this merge. But in bower.json, the tag is 1.0.6(the next number after 1.0.5)

**Comment by sshumake** [comment]
@renujhamtani we should be using published_date for comments.  Lets discuss further tomorrow.

**Comment by connyay** [comment]
@sshumake is there a prize for the 1000th jira? What does @renujhamtani win??

**Comment by renujhamtani** [comment]
@connyay Good point!!! Need something here !! Big Prize!! I can take it from you all when you are in India.

**Comment by renujhamtani** [comment]
@ardasgup @sshumake Please review this. I am using published_date instead of created_date for sorting of comments and display. This would cover both the bugs PCM-998 and PCM-1000. Once reviewed and merged, I will tag this and use this tag in PCM. ( Not able to understand the inconsistency between the version in bower.json and actual tag version. Actual tag version would be 1.0.8 once i tag after this merge. But in bower.json, the tag is 1.0.6(the next number after 1.0.5)).

**Comment by aritrod** [comment]
Reviewed!

**Comment by sshumake** [comment]
Looks good to me.

**Pull request merged**
