### PR TITLE
PCM-2726: Fix strataService.search for articles

### PR DESCRIPTION
**Pull request by engineersamuel**
PCM-2726

Updating the search function to handle articles and removing the ie8 specific code as we no longer support ie8. Also re-organizing how the caching is handled to eliminate code.

### CODE REVIEW

**Comment by engineersamuel** [comment]
@gandhikeyur @vrathee @jtrantin @pbathia please review and merge.

**Comment by engineersamuel** [comment]
Hah, it looks like when I pushed 8acb1e8 that I had a dash in the commit which created the file with the name of the next word which was 1.1.37.   That is why you see the strange "Spurious file" commit above, I had to remove that as it got added in my git add.

**Comment by gandhikeyur** [comment]
Reviewed

**Comment by vrathee** [comment]
Reviewed!

**Comment by jtrantin** [comment]
Reviewed.

**Pull request merged**
